racecar:

#  joint_front_wheel_effort_controller:
#    type: effort_controllers/JointEffortController
#    joint: joint_front_wheel
#    pid: {p: 1000.0, i: 500, d: 500.0}

  left_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_rear_axle #_WR_
    pid: {p: 1000.0, i: 0.00, d: 0.0}


  right_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_rear_axle  # NEVER POWER OFF
    pid: {p: 1000.0, i: 0.00, d: 0.0}


  left_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_front_axle
    pid: {p: 1000.0, i: 0.00, d: 0.0}


  right_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_front_axle
    pid: {p: 1000.0, i: 0.00, d: 0.0}
    
  left_steering_hinge_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_steering_joint
    pid: {p: 10000.0, i: 0.1, d: 500.0}
  
  right_steering_hinge_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_steering_joint
    pid: {p: 10000.0, i: 0.1, d: 500.0}


  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50